### ISSUE TITLE
Resolve Bower Dependency vn-toolbox-common

### ISSUE THREAD

**Issue by carsonreinke** [volusion-angular-themes/method#240]
[`vn-toolbox-common`](github.com/volusion-angular/vn-toolbox-common) is neither available publicly nor via the [volusion-angular](https://github.com/volusion-angular) group.  Please grant access to this project.

**Comment by oseibonsu** [comment]
@carsonreinke This issue is fixed in the master branch. c4be3bba063bf9f9ba5fbb6f4873c1073e91da2c

**Comment by carsonreinke** [comment]
Thank you @oseibonsu
